# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'DongerListKeyboard' do

end

target 'DongerListKeyboardTests' do

end

target 'DLKeyboard' do

end

